chore: delete all warnings
legolas-tek/r-type pull request #100
Opened 2023-10-20 21:22 UTC by LindonAliu

2023-10-20 21:36 UTC, Snowy1803 requested changes

2023-10-20 21:36 UTC, Snowy1803 commented on client/sources/main.cpp
> +int main([[maybe_unused]] int argc, [[maybe_unused]] char *argv[])
Juste change le prototype pour prendre void

2023-10-20 21:36 UTC, Snowy1803 commented on libs/engine/includes/Components/Animation.hpp
> +    float _currentOffset = 0; ///< The current index of the animation.
??????????
Une width, height, les offset et les index dans un tableau c’est absolument pas des flottants ?????!

2023-10-20 21:36 UTC, Snowy1803 commented on libs/engine/includes/Components/Controllable.hpp
> +    [[maybe_unused]] int _id = 0;
Hein ???? On l’utilisera dans ma pr hein

2023-10-20 21:36 UTC, Snowy1803 commented on libs/engine/includes/EntityInfo.hpp
> +    float offset;
Nonsense

2023-10-20 21:36 UTC, Snowy1803 commented on libs/engine/includes/Serialization/Serializer.hpp
> +        auto size = static_cast<SizeType>(str.size());
```suggestion
        SizeType size(str.size());
```
C’est beaucoup trop long les static cast…

2023-10-20 21:36 UTC, Snowy1803 commented on libs/networking/includes/LobbyServer.hpp
> +            emplaceClient(std::move(newClient));
(Ratio)

2023-10-20 21:36 UTC, Snowy1803 commented on libs/networking/sources/Snapshot.cpp
> +    diff.serializeTrivial(true);
J’ai dit non.

2023-10-20 21:36 UTC, Snowy1803 commented on libs/networking/sources/Snapshot.cpp
> +    diff.serializeTrivial(false);
De même.

2023-10-20 21:36 UTC, Snowy1803 commented on libs/networking/sources/Snapshot.cpp
> -using UpdateType = bool;
Ratio

2023-10-20 21:36 UTC, Snowy1803 commented on libs/networking/sources/Sync.cpp
> +            break;
Intérêt 0.

2023-10-20 21:36 UTC, Snowy1803 commented on libs/rtype/sources/Game.hpp
> +    [[maybe_unused]] std::size_t _playerHash = 0;
Arrête de mettre des maybe unused… on veut les garder ces warning parce que c’est pas normal qu’ils restent là, c’est juste que ça viendra plus tard.

2023-10-20 21:36 UTC, Snowy1803 commented on libs/rtype/sources/LobbyGame.cpp
> -    );
Pourquoi t’enlèves mon système ???????????
J’en ai besoin !!!!!! Dans ma pr

2023-10-20 21:36 UTC, Snowy1803 commented on libs/rtype/sources/Systems/SpawnEnemySystem.cpp
> +    auto randomY = static_cast<float>(distribY(_gen));
Quel est le fuck ??? Utilise un uniform_float_distribution au pire

2023-10-20 21:36 UTC, Snowy1803 commented on libs/rtype/sources/Systems/WaveManagerSystem.cpp
> +                450 - static_cast<int>(_entityList[0].entityHeight)
Horrible

2023-10-20 21:36 UTC, Snowy1803 commented on server/sources/main.cpp
> +int main([[maybe_unused]] int argc, [[maybe_unused]] char *argv[])
Pareil, void

2023-10-20 22:05 UTC, Snowy1803 commented on libs/engine/includes/IGame.hpp
> +    virtual void initAssets(engine::Registry &reg) = 0;
il ne doivent absolument pas être virtuels purs !!!! Comment ça compile même ??

2023-10-20 22:35 UTC, LindonAliu commented on libs/rtype/sources/Systems/SpawnEnemySystem.cpp
> +    auto randomY = static_cast<float>(distribY(_gen));
ça existe pas

2023-10-20 23:38 UTC, LindonAliu commented on libs/engine/includes/Serialization/Serializer.hpp
> +        auto size = static_cast<SizeType>(str.size());
C:\development\r-type\libs\engine\.\includes\Serialization/Serializer.hpp(42): warning C4267: 'initialisation' : conversion de 'size_t' en 'uint8_t', perte possible de données
c'est pour ça que j'ai fais un static cast sinon ça me fait ça

2023-10-20 23:49 UTC, Snowy1803 commented on libs/rtype/sources/Systems/SpawnEnemySystem.cpp
> +    auto randomY = static_cast<float>(distribY(_gen));
https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution

2023-10-21 00:06 UTC, Snowy1803 commented on libs/engine/includes/IGame.hpp
> +    }
pour le coup un jeu sans component bon

2023-10-21 00:06 UTC, Snowy1803 commented on libs/engine/sources/Systems/CollisionsSystem.cpp
> +        collision.value()._collidingEntity = std::nullopt;
```suggestion
        collision->_collidingEntity = std::nullopt;
```
tant qu'à faire

2023-10-21 00:06 UTC, Snowy1803 commented on libs/networking/sources/Sync.cpp
> +            break;
toujours pas d'interet d'ecrire default si c'est pour rien mettre dedans

2023-10-21 00:06 UTC, Snowy1803 commented on libs/rtype/sources/Systems/SpawnEnemySystem.cpp
> +    auto randomY = static_cast<float>(distribY(_gen));
non mais juste, generer un int pour le cast en float c'est bizarre

2023-10-21 00:47 UTC, Snowy1803 approved these changes

2023-10-21 00:47 UTC, Snowy1803 commented on libs/rtype/sources/Systems/SpawnEnemySystem.cpp
> +            _entityInfo.textureIndex, float(_entityInfo.entityWidth),
Pourquoi c’est pas des float dans la struct là

2023-10-21 01:21 UTC, Snowy1803 approved these changes

2023-10-21 01:27 UTC, merged