feat: clients use the t - 1 update
legolas-tek/r-type pull request #159
Opened 2023-11-01 22:25 UTC by jeremyelalouf

2023-11-02 00:11 UTC, Snowy1803 commented on libs/networking/sources/Sync.cpp
> +                _lastUpdate = std::move(buffer);
Tu le vide pas ici ? Pourquoi tu le move a deux endroits

2023-11-02 00:22 UTC, jeremyelalouf commented on libs/networking/sources/Sync.cpp
> +                _lastUpdate = std::move(buffer);
t'es sur t'a tout lu ? je le move que ici, dans le cas ou je suis un client. sauf dans le premier if qui est juste là pour gérer le cas ou j'ai reçu qu'une update

2023-11-02 00:23 UTC, Snowy1803 approved these changes

2023-11-02 00:23 UTC, Snowy1803 commented on libs/networking/sources/Sync.cpp
> +                _lastUpdate = std::move(buffer);
Ah okok

2023-11-03 20:13 UTC, badermarouan approved these changes

2023-11-04 15:42 UTC, LindonAliu approved these changes

2023-11-04 20:56 UTC, Snowy1803 requested changes

2023-11-04 20:56 UTC, Snowy1803 commented on libs/engine/includes/Components/Velocity.hpp
> +        ser.serializeTrivial<Velocity>(*this);
Bah non, serialise _vx et _vy…..

2023-11-04 20:56 UTC, Snowy1803 commented on libs/engine/includes/Components/Velocity.hpp
> +        deser.deserializeTrivial<Velocity>(*this);
Pareil

2023-11-04 20:56 UTC, Snowy1803 commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
wtf

2023-11-04 20:56 UTC, Snowy1803 commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
Le *principe* de l’interpolation c’est qu’on a deux positions et on calcule une vélocité entre les deux, en traçant une droite

2023-11-04 21:06 UTC, jeremyelalouf commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
ok mais moi là j'ai accès a aucune position, j'ai accès à la velocitée actuelle et la velocitée future

2023-11-04 21:08 UTC, Snowy1803 commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
C’est pour ça qu’on avait dit qu’il fallait override serialisable de position pas de vélocité ? Ça sert à rien d’avoir le vélocité future ? Fin si faudrait la set a la fin quoi mais Sync s’en charge non ?

2023-11-04 21:12 UTC, jeremyelalouf commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
euh non on parlait que de vélocités... donc il faut faire ça a partir des positions ?

et donc quand tu dis set la vélocité future à la fin càd ?

2023-11-04 21:18 UTC, Snowy1803 commented on libs/networking/sources/Interpolate.cpp
> +        it->_vy += (it->_futurVy / 8);
non rien

2023-11-05 01:32 UTC, Snowy1803 commented on libs/engine/includes/Components/Position.hpp
> +        _futurY = futurY;
c'est quoi ça ? un std::swap ?

2023-11-05 01:32 UTC, Snowy1803 commented on libs/engine/includes/Components/Position.hpp
> +        _futurY = futurY;
je pense pas que ça marche ça ?
swap avant et deserialize dans _futureX directement ?

2023-11-05 01:32 UTC, Snowy1803 commented on libs/engine/includes/Components/Position.hpp
> +    float _futurX = 0;
future

2023-11-05 01:32 UTC, Snowy1803 commented on libs/networking/sources/Interpolate.cpp
> +        vel->_vy = pos._futurY - pos._y / 2;
genre t'auras un update tous les 2 ticks... c'est 6 ton timestep

2023-11-05 22:37 UTC, closed without merging