Feature/mario game
legolas-tek/r-type pull request #170
Opened 2023-11-03 20:31 UTC by yunse-lee-EPITECH

closes: #152

2023-11-04 20:58 UTC, Snowy1803 commented on client/CMakeLists.txt
> +    mario
Ce serait bien de ne pas remplacer rtype, mais plutôt de faire une option() pour qu’on puisse choisir…

2023-11-05 17:31 UTC, LindonAliu requested changes

2023-11-05 17:31 UTC, LindonAliu commented on libs/engine/sources/Systems/MoveSystem.cpp
> +        = _velocities[collidingEntity].value();
tu check pas si les .value() existent donc ça crash, pareil pour l'autre
la canMove ne fonctionne pas sur le RType avec les murs aussi

2023-11-05 17:31 UTC, LindonAliu commented on libs/engine/sources/Systems/MoveSystem.cpp
> +        = _velocities[collidingEntity].value();
tu check pas tes values, donc ça crash ici, et le canMove ne fonctionne pas sur le rtype

2023-11-05 20:17 UTC, Snowy1803 commented on libs/engine/sources/Systems/MoveSystem.cpp
> +#include <iostream>
...

2023-11-05 21:34 UTC, LindonAliu commented on libs/engine/includes/Events/Key.hpp
> +#include <iostream>
doit pas être là

2023-11-05 21:34 UTC, LindonAliu commented on libs/engine/sources/Systems/GravitySystem.cpp
> +        if ((*it)->isOffset == false) {
```suggestion
       if (not (*it)->isOffset)
```

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/JumpSystem.cpp
> +        }
```suggestion
        (*it)->canJump = isOnSolid(it.get_entity();
```

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/JumpSystem.cpp
> +}
pas implémenter c'est normal ?

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/JumpSystem.cpp
> +                _velocities[it.get_entity()]->_vy -= 5;
tu peux peut-être use les events qu'a fait jerem, essaye de voir avec lui

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/KeyHandleSystem.cpp
> +}
pareil pr ça essaye de voir avec jerem pour remplacer ça par les events

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/MarioGame.cpp
> +    for (int i = 0; i < 82; ++i) {
bien magic value

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/RailSystem.cpp
> +                _velocities[it.get_entity()]->_vx = 0.0f;
same ici, essaye d'utiliser le code qu'a fait jerem si tu veux que ça se reset etc

2023-11-05 21:34 UTC, LindonAliu commented on libs/mario/sources/Systems/RailSystem.cpp
> +        _velocities[entity]->_vx = 0.0f;
en fait à chaque fois que tu touches à une velocité essaye d'utiliser les events comme ça ça se reset

2023-11-05 21:34 UTC, LindonAliu commented on libs/rendering/sources/Key.cpp
> +#include <iostream>
pas ça

2023-11-05 22:05 UTC, LindonAliu commented on libs/mario/sources/Systems/JumpSystem.cpp
> +        }
enfin, ça dépend de ce que tu veux

2023-11-05 22:07 UTC, yunse-lee-EPITECH commented on libs/mario/sources/Systems/JumpSystem.cpp
> +}
oui

2023-11-05 22:07 UTC, yunse-lee-EPITECH commented on libs/mario/sources/Systems/JumpSystem.cpp
> +                _velocities[it.get_entity()]->_vy -= 5;
aucun rapport je t'avais expliquer hier et tous le mode etait d'acc

2023-11-05 22:07 UTC, yunse-lee-EPITECH commented on libs/mario/sources/Systems/KeyHandleSystem.cpp
> +}
aussi

2023-11-05 22:08 UTC, yunse-lee-EPITECH commented on libs/mario/sources/MarioGame.cpp
> +    for (int i = 0; i < 82; ++i) {
c dans init scene comment de ne pas avoir

2023-11-05 22:08 UTC, yunse-lee-EPITECH commented on libs/mario/sources/Systems/RailSystem.cpp
> +                _velocities[it.get_entity()]->_vx = 0.0f;
non c pour stop

2023-11-05 22:14 UTC, badermarouan approved these changes

2023-11-05 22:24 UTC, LindonAliu approved these changes

2023-11-05 22:24 UTC, merged